### ISSUE TITLE
`Lib` exported

### ISSUE THREAD

**Issue by phadej** [andrewthad/impure-containers#2]
https://github.com/andrewthad/impure-containers/blob/c930e221918de21aedfedec68e53946bd406107b/impure-containers.cabal#L19

It's great that you put stuff for others on Hackage, but please, use a bit of time to clean it up :)

**Comment by andrewthad** [comment]
This is now fixed. I'll close this once I release a new version to hackage.

**Comment by andrewthad** [comment]
http://hackage.haskell.org/package/impure-containers-0.2
